spring:
  application:
    name: football-stream

  datasource:
    url: jdbc:postgresql://localhost:5432/football_analytics
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: football-stream-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  thymeleaf:
    cache: false

server:
  port: 8080

football-data:
  api:
    base-url: https://api.football-data.org/v4
    token: ${FOOTBALL_DATA_TOKEN:}
    leagues: PL,PD,SA,BL1,FL1